/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.Servicio;
import DAO.ServicioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ServiciosAdd extends javax.swing.JFrame {
    private ServicioDAO dao = new ServicioDAO();
    
    LibrosList librosList;
    LibrosAdd librosAdd;
    
    EmpleadosAdd empleadosAdd;
    EmpleadosList empleadosList;
    
    ServiciosAdd serviciosAdd;
    ServiciosList serviciosList;
    
    SolicitudesList solicitudesList;
    SolicitudesAdd solicitudesAdd;
    
    DespachosList despachosList;
    
    public ServiciosAdd() {
        initComponents();
        
        empleadosAdd = new EmpleadosAdd();
        empleadosList = new EmpleadosList();
        
        librosList = new LibrosList();
        librosAdd = new LibrosAdd();
        
        serviciosAdd = new ServiciosAdd();
        serviciosList = new ServiciosList();
        
        solicitudesList = new SolicitudesList();
        solicitudesAdd = new SolicitudesAdd();
        
        despachosList = new DespachosList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtHeading = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputDescp = new javax.swing.JTextArea();
        btnClean = new javax.swing.JButton();
        inputPrice = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuWorkers = new javax.swing.JMenu();
        btnListWorkers = new javax.swing.JMenuItem();
        btnAddWorkers = new javax.swing.JMenuItem();
        MenuBooks = new javax.swing.JMenu();
        btnListBooks = new javax.swing.JMenuItem();
        btnAddBooks = new javax.swing.JMenuItem();
        MenuServices = new javax.swing.JMenu();
        btnListServices = new javax.swing.JMenuItem();
        btnAddServices = new javax.swing.JMenuItem();
        MenuRequest = new javax.swing.JMenu();
        btnListRequest = new javax.swing.JMenuItem();
        btnAddRequest = new javax.swing.JMenuItem();
        MenuDispacth = new javax.swing.JMenu();
        btnListDispacht = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 217));

        txtHeading.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        txtHeading.setForeground(new java.awt.Color(0, 0, 153));
        txtHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHeading.setText("Servicios");

        txtName.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtName.setText("Nombre:");

        inputName.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        txtCategory.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtCategory.setText("Descripción:");

        txtPrice.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txtPrice.setText("Precio:");

        btnAdd.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        inputDescp.setColumns(20);
        inputDescp.setRows(5);
        jScrollPane2.setViewportView(inputDescp);

        btnClean.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnClean.setText("Limpiar");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputName)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClean))
                    .addComponent(inputPrice))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPrice)
                .addGap(18, 18, 18)
                .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClean))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        MenuWorkers.setText("Empleados");

        btnListWorkers.setText("Lista");
        btnListWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListWorkersActionPerformed(evt);
            }
        });
        MenuWorkers.add(btnListWorkers);

        btnAddWorkers.setText("Agregar");
        btnAddWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkersActionPerformed(evt);
            }
        });
        MenuWorkers.add(btnAddWorkers);

        jMenuBar1.add(MenuWorkers);

        MenuBooks.setText("Libros");

        btnListBooks.setText("Lista");
        btnListBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListBooksActionPerformed(evt);
            }
        });
        MenuBooks.add(btnListBooks);

        btnAddBooks.setText("Agregar");
        btnAddBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBooksActionPerformed(evt);
            }
        });
        MenuBooks.add(btnAddBooks);

        jMenuBar1.add(MenuBooks);

        MenuServices.setText("Servicios");

        btnListServices.setText("Lista");
        btnListServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListServicesActionPerformed(evt);
            }
        });
        MenuServices.add(btnListServices);

        btnAddServices.setText("Agregar");
        btnAddServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServicesActionPerformed(evt);
            }
        });
        MenuServices.add(btnAddServices);

        jMenuBar1.add(MenuServices);

        MenuRequest.setText("Solicitudes");

        btnListRequest.setText("Lista");
        btnListRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRequestActionPerformed(evt);
            }
        });
        MenuRequest.add(btnListRequest);

        btnAddRequest.setText("Agregar");
        btnAddRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRequestActionPerformed(evt);
            }
        });
        MenuRequest.add(btnAddRequest);

        jMenuBar1.add(MenuRequest);

        MenuDispacth.setText("Despacho");

        btnListDispacht.setText("Lista");
        btnListDispacht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListDispachtActionPerformed(evt);
            }
        });
        MenuDispacth.add(btnListDispacht);

        jMenuBar1.add(MenuDispacth);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String nombre = inputName.getText();
        String descrp = inputDescp.getText();
        int precio = (int)inputPrice.getValue();
        
        Servicio serv = new Servicio (nombre,descrp,precio);
        
        try {
            if (dao.guardarServicio(serv)) {
                JOptionPane.showMessageDialog(this, "Servicio Guardado");
            } else {
                JOptionPane.showMessageDialog(this, "Servicio No Guardado");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
            Logger.getLogger(ServiciosAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        JOptionPane.showMessageDialog(this, "Empleado Registrado");
        Limpiar();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnListWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListWorkersActionPerformed
        empleadosList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListWorkersActionPerformed

    private void btnAddWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkersActionPerformed
        empleadosAdd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddWorkersActionPerformed

    private void btnListBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListBooksActionPerformed
        librosList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListBooksActionPerformed

    private void btnAddBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBooksActionPerformed
        librosAdd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddBooksActionPerformed

    private void btnListServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListServicesActionPerformed
        serviciosList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListServicesActionPerformed

    private void btnAddServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServicesActionPerformed
        serviciosAdd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddServicesActionPerformed

    private void btnListRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRequestActionPerformed
        serviciosList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListRequestActionPerformed

    private void btnAddRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRequestActionPerformed
        solicitudesAdd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddRequestActionPerformed

    private void btnListDispachtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListDispachtActionPerformed
        solicitudesList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListDispachtActionPerformed

    private void Limpiar(){
        inputName.setText("");
        inputPrice.setValue(0);
        inputDescp.setText("");
   }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiciosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiciosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiciosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiciosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiciosAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBooks;
    private javax.swing.JMenu MenuDispacth;
    private javax.swing.JMenu MenuRequest;
    private javax.swing.JMenu MenuServices;
    private javax.swing.JMenu MenuWorkers;
    private javax.swing.JButton btnAdd;
    private javax.swing.JMenuItem btnAddBooks;
    private javax.swing.JMenuItem btnAddRequest;
    private javax.swing.JMenuItem btnAddServices;
    private javax.swing.JMenuItem btnAddWorkers;
    private javax.swing.JButton btnClean;
    private javax.swing.JMenuItem btnListBooks;
    private javax.swing.JMenuItem btnListDispacht;
    private javax.swing.JMenuItem btnListRequest;
    private javax.swing.JMenuItem btnListServices;
    private javax.swing.JMenuItem btnListWorkers;
    private javax.swing.JTextArea inputDescp;
    private javax.swing.JTextField inputName;
    private javax.swing.JSpinner inputPrice;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtCategory;
    private javax.swing.JLabel txtHeading;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPrice;
    // End of variables declaration//GEN-END:variables
}
